services:
  postgres:
    image: postgres:17.6-alpine
    container_name: pepperminto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pepperminto
      POSTGRES_PASSWORD: pepperminto
      POSTGRES_DB: pepperminto
    volumes:
      - pepperminto_postgres:/var/lib/postgresql/data
    expose:
      - 5432

  api:
    image: nulldoubt/pepperminto-api:latest
    container_name: pepperminto_api
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - postgres
    env_file: .env
    environment:
      DATABASE_URL: postgresql://pepperminto:pepperminto@postgres:5432/pepperminto
    ports:
      - "3001:3001"

  client:
    image: nulldoubt/pepperminto-client:latest
    container_name: pepperminto_client
    restart: unless-stopped
    env_file: .env
    ports:
      - "3002:3002"

  knowledge-base:
    image: nulldoubt/pepperminto-knowledge-base:latest
    container_name: pepperminto_kb
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"

  docs:
    image: nulldoubt/pepperminto-docs:latest
    container_name: pepperminto_docs
    restart: unless-stopped
    env_file: .env
    ports:
      - "3003:3003"

  landing-page:
    image: nulldoubt/pepperminto-landing-page:latest
    container_name: pepperminto_landing
    restart: unless-stopped
    env_file: .env
    ports:
      - "3004:3004"

volumes:
  pepperminto_postgres:
